baseURL = "http://oba.github.io/"
copyright = "Kendal Harland"
languageCode = "en-us"
title = "Oba"
theme = "whisper"

[params]
  colortheme = "white"
  homepage_button_link = "/guides/language"
  homepage_button_text = "Language Tour"
  homepage_intro = "A lightweight, fast, embeddable, functional scripting language."

[params.logo]
  standard = "/images/logo.png"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Learn"
url = "/guides/language/"
weight = 1

[[menu.main]]
name = "Source"
url =  "https://github.com/kendalharland/oba"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

